version: '3.9'

services:
  backend:
    build:
      context: .
      target: ${NODE_ENV:-development}
    container_name: eto_backend
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      LOGIN_JWT_EXPIRES_SECONDS: ${LOGIN_JWT_EXPIRES_SECONDS}
      OTP_JWT_EXPIRES_SECONDS: ${OTP_JWT_EXPIRES_SECONDS}
      ENABLE_DOCS: ${ENABLE_DOCS}
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "8888:8888"
      - "9229:9229"
    volumes:
      - .:/app
      - /app/node_modules
      - assets:/app/eto_assets
      - logs:/app/logs
    networks:
      - network
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:17.4
    container_name: eto_db
    environment:
      POSTGRES_USER: ${DB_USERNAME:-eto}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-eto_db}
    ports:
      - "5435:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-eto}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db:
  assets:
  backend:
  logs:

networks:
  network:
    driver: bridge